### ISSUE TITLE
copy shortcut

### ISSUE THREAD

**Issue by kirkkwang** [nkantar/mdut#15]
as a user: i want to see a link and press a special keyboard shortcut to activate mdut and copy the link, then go to my .md and paste it in there with all the syntax

**Comment by nkantar** [comment]
Honestly, that's quite far out of scope for such a small tool. I have a couple of ideas, though.

The first is **[bookmarklets](https://en.wikipedia.org/wiki/Bookmarklet "Bookmarklet - Wikipedia")**. My guess is that this is the easiest way to get what you want, especially if you only care about this functionality existing from within the browser. Some useful resources can be found [here](https://caiorss.github.io/bookmarklets "BOOKMARKLETS").

The second is **OS automation**. In the past I've used **[Alfred](https://www.alfredapp.com/ "Alfred - Productivity App for macOS")** and currently have checking out **[Hammerspoon](https://www.hammerspoon.org/ "Hammerspoon")** on my to-do list. Creating an automation that would grab the selected text and feed it to `mdut` should accomplish your goal.
